"""Change fields to string

Revision ID: b785d4f68ae7
Revises: c0137104ae79
Create Date: 2026-03-28 07:06:12.828925

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b785d4f68ae7'
down_revision: Union[str, Sequence[str], None] = 'c0137104ae79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle', 'ano',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('vehicle', 'preco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('vehicle', 'km',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle', 'km',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('vehicle', 'preco',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('vehicle', 'ano',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
